#! /bin/sh
# /etc/init.d/noip

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will sta$
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
sudo /home/pi/remote/watcher.sh &
exit 0
